import type { Locale } from "./i18n";

const en = {
  meta: { title: "MIKEO | Brand & product showcase", description: "Explore the MIKEO brand and provisional product portfolio for international agents and distributors." },
  nav: { products: "Products", about: "About MIKEO", standards: "Standards", distributors: "For distributors", contact: "Contact", home: "Home", main: "Main navigation", mobile: "Mobile navigation", footer: "Footer navigation", open: "Open main menu", close: "Close main menu", skip: "Skip to main content", language: "Change language" },
  common: { sample: "Sample information", productPreparing: "Product information is being prepared.", documentsPreparing: "Verified documents are being prepared.", contactUpdating: "Official contact channels are being updated.", imagesPreparing: "Product images will be added after verification.", viewProducts: "View products", contact: "Contact us", viewDetails: "View information structure", all: "All categories", updating: "Information is being prepared." },
  announcement: "Brand and product showcase for international agents and distributors · Detailed information is under verification",
  footer: { tagline: "Making everyday self-care easier, more enjoyable, and more confident.", channels: "Contact channels", descriptor: "Brand and product showcase" },
  home: {
    note: "MIKEO · Brand & product showcase",
    title: "Everyday self-care, made easier, brighter, and more confident.",
    intro: "Discover MIKEO and explore the planned product portfolio for international agents and distributors.",
    heroVisual: "Illustrative product display area. Verified product images are being prepared.",
    visualCaption: "Neutral sample visuals only — not actual MIKEO packaging",
    verificationTitle: "Verified information comes first.",
    verificationBody: "Product details, documents, and standards will be published only after their sources are confirmed.",
    verificationLink: "See our verification approach",
    discoveryTitle: "Explore the product portfolio",
    discoveryIntro: "Browse the four provisional categories. Every item is clearly marked while verified product information is being prepared.",
    catalogLink: "View the full catalog",
    categoriesTitle: "Provisional product categories",
    categoriesIntro: "Four categories provide the initial catalog structure. Final products will be added only after verification.",
    storyTitle: "Self-care designed for real routines",
    storyBody: "MIKEO brings wellness, body care, skincare, and beauty into an approachable daily ritual, with enjoyable products created for the real routines of Thai consumers.",
    storyLink: "Meet MIKEO",
    brandImage: "Reserved area for an approved MIKEO brand image",
    brandImageTitle: "Brand imagery is being prepared.",
    brandImageNote: "Approved photography will be added when available.",
    standardsTitle: "Clarity before claims",
    standardsBody: "MIKEO will publish product information, documents, and standards only when each source has been verified.",
    standardsLink: "View information and standards",
    standardsPoints: ["Clearly separate sample content from verified information.", "Never display unsupported registration details, documents, or claims.", "Update each product when source documents are available."],
    distributorTitle: "Interested in growing with MIKEO?",
    distributorBody: "Partnership information for international agents and distributors is being prepared. Review the current business information structure.",
    distributorLink: "Information for distributors",
    contactTitle: "Start a business conversation",
  },
  products: { title: "MIKEO product portfolio", intro: "Explore the provisional category structure for international agents and distributors. Verified product details are being collected and reviewed.", noticeTitle: "Information status: sample structure", noticeBody: "The items below are not actual product names or packaging. No prices, claims, ingredients, regulatory details, or certifications are displayed.", filterLabel: "Filter products by category", showing: "Showing {count} sample items.", emptyTitle: "No sample items in this category", emptyBody: "Product information is being prepared.", reset: "View all categories" },
  product: { back: "Back to products", pageTitle: "Sample product information", category: "Provisional category", status: "Information status", statusBody: "This page demonstrates the future product-information structure only.", sections: ["Product overview", "Ingredients", "Directions and cautions", "Regulatory and verification information"], sectionBody: "Product information is being prepared.", imageAlt: "Neutral sample product visual, not actual MIKEO packaging", missingTitle: "Product not found", missingBody: "The requested sample product is unavailable or the address may be incorrect.", missingLink: "Return to products" },
  about: { title: "MIKEO in everyday self-care", intro: "A Thai brand bringing wellness, body care, skincare, and beauty into approachable everyday routines.", values: "Spirited.\nEncouraging.\nTransparent.", philosophyTitle: "Our brand idea", philosophyBody: "MIKEO believes self-care should feel approachable rather than complicated. The brand experience is designed to be lively, welcoming, and relevant to real daily routines.", priorityTitle: "What matters to us", priorityBody: "Communication should be clear, respectful, and transparent about what is verified and what is still being prepared.", pending: "Founder details and the full approved brand history are being prepared." },
  standards: { title: "Verifiable information, communicated clearly", intro: "A dedicated place for verified product documents, standards, and supporting information—without substituting assumptions for evidence.", currentTitle: "Current information status", currentBody: "Product-specific information and supporting documents are being collected and verified.", principlesTitle: "Publication principles", steps: [["Receive source materials", "Wait for documents or information from the relevant information owner."], ["Review for completeness", "Separate verifiable information from content that remains unconfirmed."], ["Publish with status", "Present only suitable information with clear, accessible context."]] },
  distributors: { title: "Explore business opportunities with MIKEO", intro: "Provisional information for international agents, distributors, and partners. No income claims, commercial terms, or eligibility conditions are presented before verification.", materialsTitle: "Information being prepared for partners", materials: ["Brand and provisional portfolio overview", "Verified product information and source documents", "Market scope and partnership formats", "Business inquiry and initial review process"], statusTitle: "Distributor material status", statusBody: "Requirements, terms, and supporting documents have not yet been approved for publication." },
  contact: { title: "Contact MIKEO", intro: "This page will provide verified business contact channels. No official email address, phone number, messaging account, or external URL is currently available for publication.", prepareTitle: "Prepare for a business inquiry", prepareBody: "Prospective partners can prepare their country, market, organization, and preferred partnership format before contacting MIKEO.", note: "A contact form will be added only when a verified destination and data-handling process are available." },
  states: { loading: "Loading page…", errorTitle: "We could not load this page", errorBody: "Please try again. No information has been submitted or changed.", retry: "Try again", notFoundTitle: "Page not found", notFoundBody: "The page may have moved or the address may be incorrect.", home: "Return home" },
};

export type Dictionary = typeof en;

const th: Dictionary = {
  meta: { title: "MIKEO | แบรนด์และผลิตภัณฑ์", description: "สำรวจแบรนด์ MIKEO และโครงสร้างผลิตภัณฑ์สำหรับตัวแทนและผู้จัดจำหน่ายต่างประเทศ" },
  nav: { products: "ผลิตภัณฑ์", about: "เกี่ยวกับ MIKEO", standards: "มาตรฐาน", distributors: "สำหรับตัวแทน", contact: "ติดต่อเรา", home: "หน้าหลัก", main: "เมนูหลัก", mobile: "เมนูหลักบนมือถือ", footer: "เมนูส่วนท้าย", open: "เปิดเมนูหลัก", close: "ปิดเมนูหลัก", skip: "ข้ามไปยังเนื้อหาหลัก", language: "เปลี่ยนภาษา" },
  common: { sample: "ข้อมูลตัวอย่าง", productPreparing: "กำลังจัดเตรียมข้อมูลผลิตภัณฑ์", documentsPreparing: "กำลังจัดเตรียมเอกสารที่ผ่านการตรวจสอบ", contactUpdating: "กำลังอัปเดตช่องทางติดต่ออย่างเป็นทางการ", imagesPreparing: "จะเพิ่มรูปสินค้าหลังจากตรวจสอบแล้ว", viewProducts: "ดูผลิตภัณฑ์", contact: "ติดต่อเรา", viewDetails: "ดูโครงสร้างข้อมูล", all: "ทุกหมวดหมู่", updating: "กำลังจัดเตรียมข้อมูล" },
  announcement: "เว็บไซต์แสดงข้อมูลแบรนด์และผลิตภัณฑ์สำหรับตัวแทนและผู้จัดจำหน่ายต่างประเทศ · รายละเอียดอยู่ระหว่างการตรวจสอบ",
  footer: { tagline: "ให้ทุกวันของการดูแลตัวเอง ง่ายขึ้น สนุกขึ้น และมั่นใจขึ้น", channels: "ช่องทางติดต่อ", descriptor: "เว็บไซต์แสดงข้อมูลแบรนด์และผลิตภัณฑ์" },
  home: { note: "MIKEO · Brand & product showcase", title: "ให้ทุกวันของการดูแลตัวเอง ง่ายขึ้น สนุกขึ้น และมั่นใจขึ้น", intro: "ทำความรู้จักแบรนด์ MIKEO และสำรวจโครงสร้างกลุ่มผลิตภัณฑ์สำหรับตัวแทนและผู้จัดจำหน่ายต่างประเทศ", heroVisual: "พื้นที่แสดงผลิตภัณฑ์ตัวอย่าง กำลังจัดเตรียมรูปผลิตภัณฑ์ที่ผ่านการตรวจสอบ", visualCaption: "ภาพตัวอย่างเพื่อแสดงโครงสร้างเท่านั้น ไม่ใช่บรรจุภัณฑ์จริง", verificationTitle: "ให้ความสำคัญกับข้อมูลที่ตรวจสอบได้", verificationBody: "รายละเอียดผลิตภัณฑ์ เอกสาร และมาตรฐานจะเผยแพร่เมื่อยืนยันแหล่งที่มาแล้วเท่านั้น", verificationLink: "ดูแนวทางการตรวจสอบ", discoveryTitle: "สำรวจโครงสร้างผลิตภัณฑ์", discoveryIntro: "เลือกดูสี่หมวดหมู่เบื้องต้น ทุกรายการมีป้ายกำกับชัดเจนระหว่างจัดเตรียมข้อมูลที่ผ่านการตรวจสอบ", catalogLink: "ดูแคตตาล็อกทั้งหมด", categoriesTitle: "กลุ่มผลิตภัณฑ์เบื้องต้น", categoriesIntro: "สี่หมวดหมู่สำหรับวางโครงสร้างแคตตาล็อก รายการจริงจะเพิ่มเมื่อได้รับข้อมูลที่ยืนยันแล้ว", storyTitle: "การดูแลตัวเองที่เข้ากับทุกวันจริง", storyBody: "MIKEO นำเวลเนส บอดี้แคร์ สกินแคร์ และความงามมารวมไว้ในกิจวัตรประจำวันที่เข้าถึงง่าย ด้วยผลิตภัณฑ์ที่ตั้งใจสร้างให้เข้ากับชีวิตจริงของผู้บริโภคชาวไทย", storyLink: "รู้จัก MIKEO", brandImage: "พื้นที่สำหรับภาพแบรนด์ MIKEO ที่ได้รับอนุมัติ", brandImageTitle: "กำลังจัดเตรียมภาพแบรนด์", brandImageNote: "จะแสดงเมื่อได้รับไฟล์ที่ได้รับอนุมัติ", standardsTitle: "ความชัดเจนก่อนการกล่าวอ้าง", standardsBody: "MIKEO จะเผยแพร่ข้อมูลผลิตภัณฑ์ เอกสาร และมาตรฐานเฉพาะรายการที่ตรวจสอบแหล่งที่มาแล้วเท่านั้น", standardsLink: "ดูข้อมูลและมาตรฐาน", standardsPoints: ["แยกข้อมูลตัวอย่างออกจากข้อมูลที่ยืนยันแล้วอย่างชัดเจน", "ไม่แสดงเลขทะเบียน เอกสาร หรือข้อกล่าวอ้างที่ยังไม่มีแหล่งอ้างอิง", "อัปเดตข้อมูลรายผลิตภัณฑ์เมื่อได้รับเอกสารต้นทาง"], distributorTitle: "สนใจร่วมเติบโตกับ MIKEO", distributorBody: "ข้อมูลสำหรับตัวแทนและผู้จัดจำหน่ายต่างประเทศอยู่ระหว่างการจัดเตรียม คุณสามารถดูโครงสร้างความร่วมมือเบื้องต้นได้", distributorLink: "ข้อมูลสำหรับตัวแทน", contactTitle: "เริ่มต้นบทสนทนาทางธุรกิจ" },
  products: { title: "โครงสร้างผลิตภัณฑ์ MIKEO", intro: "สำรวจหมวดหมู่เบื้องต้นสำหรับตัวแทนและผู้จัดจำหน่ายต่างประเทศ ข้อมูลผลิตภัณฑ์จริงกำลังอยู่ระหว่างการรวบรวมและตรวจสอบ", noticeTitle: "สถานะข้อมูล: ตัวอย่างโครงสร้าง", noticeBody: "รายการด้านล่างไม่ใช่ชื่อหรือบรรจุภัณฑ์ผลิตภัณฑ์จริง และไม่มีการแสดงราคา ข้อกล่าวอ้าง ส่วนผสม ข้อมูลกำกับดูแล หรือการรับรอง", filterLabel: "กรองผลิตภัณฑ์ตามหมวดหมู่", showing: "แสดง {count} รายการ — ข้อมูลทั้งหมดเป็นตัวอย่างโครงสร้าง", emptyTitle: "ยังไม่มีข้อมูลในหมวดหมู่นี้", emptyBody: "กำลังจัดเตรียมข้อมูลผลิตภัณฑ์", reset: "ดูทุกหมวดหมู่" },
  product: { back: "กลับไปหน้าผลิตภัณฑ์", pageTitle: "ข้อมูลผลิตภัณฑ์ตัวอย่าง", category: "หมวดหมู่เบื้องต้น", status: "สถานะข้อมูล", statusBody: "หน้านี้แสดงโครงสร้างข้อมูลผลิตภัณฑ์ในอนาคตเท่านั้น", sections: ["ภาพรวมผลิตภัณฑ์", "ส่วนผสม", "วิธีใช้และข้อควรระวัง", "ข้อมูลกำกับดูแลและการตรวจสอบ"], sectionBody: "กำลังจัดเตรียมข้อมูลผลิตภัณฑ์", imageAlt: "ภาพผลิตภัณฑ์ตัวอย่างที่เป็นกลาง ไม่ใช่บรรจุภัณฑ์จริงของ MIKEO", missingTitle: "ไม่พบผลิตภัณฑ์", missingBody: "รายการตัวอย่างที่ต้องการไม่มีอยู่หรือที่อยู่อาจไม่ถูกต้อง", missingLink: "กลับไปหน้าผลิตภัณฑ์" },
  about: { title: "MIKEO ในทุกวันของการดูแลตัวเอง", intro: "แบรนด์ไทยที่นำเวลเนส บอดี้แคร์ สกินแคร์ และความงามมารวมไว้ในกิจวัตรประจำวันที่เข้าถึงง่าย", values: "มีชีวิตชีวา\nส่งเสริมกำลังใจ\nโปร่งใส", philosophyTitle: "แนวคิดของแบรนด์", philosophyBody: "MIKEO เชื่อว่าการดูแลตัวเองไม่จำเป็นต้องซับซ้อน ประสบการณ์ของแบรนด์จึงเป็นมิตร สนุก และสอดคล้องกับกิจวัตรจริงในแต่ละวัน", priorityTitle: "สิ่งที่เราให้ความสำคัญ", priorityBody: "การสื่อสารต้องชัดเจน เคารพผู้รับข้อมูล และแยกข้อมูลที่ยืนยันแล้วออกจากข้อมูลที่ยังอยู่ระหว่างการตรวจสอบเสมอ", pending: "กำลังจัดเตรียมข้อมูลผู้ก่อตั้งและประวัติแบรนด์ฉบับเต็มที่ได้รับอนุมัติ" },
  standards: { title: "ข้อมูลที่ตรวจสอบได้ สื่อสารอย่างตรงไปตรงมา", intro: "พื้นที่สำหรับเอกสาร มาตรฐาน และข้อมูลรายผลิตภัณฑ์ที่ผ่านการตรวจสอบ โดยไม่สร้างหลักฐานหรือข้อกล่าวอ้างทดแทนข้อมูลจริง", currentTitle: "สถานะข้อมูลปัจจุบัน", currentBody: "ข้อมูลและเอกสารเฉพาะผลิตภัณฑ์กำลังอยู่ระหว่างการรวบรวมและยืนยัน", principlesTitle: "หลักการเผยแพร่ข้อมูล", steps: [["รับข้อมูลต้นทาง", "รอเอกสารหรือข้อมูลจากเจ้าของข้อมูลที่เกี่ยวข้อง"], ["ตรวจสอบความครบถ้วน", "แยกข้อมูลที่ตรวจสอบได้ออกจากเนื้อหาที่ยังไม่ยืนยัน"], ["เผยแพร่พร้อมสถานะ", "แสดงเฉพาะข้อมูลที่เหมาะสม พร้อมบริบทที่เข้าใจง่าย"]] },
  distributors: { title: "สำรวจโอกาสทางธุรกิจกับ MIKEO", intro: "ข้อมูลเบื้องต้นสำหรับตัวแทน ผู้จัดจำหน่าย และพันธมิตรต่างประเทศ โดยไม่มีการกล่าวอ้างรายได้ เงื่อนไขทางการค้า หรือคุณสมบัติที่ยังไม่ได้รับการยืนยัน", materialsTitle: "ข้อมูลที่กำลังจัดเตรียมสำหรับคู่ค้า", materials: ["ภาพรวมแบรนด์และกลุ่มผลิตภัณฑ์เบื้องต้น", "ข้อมูลผลิตภัณฑ์และเอกสารที่ผ่านการตรวจสอบ", "ขอบเขตตลาดและรูปแบบความร่วมมือ", "กระบวนการติดต่อและพิจารณาเบื้องต้น"], statusTitle: "สถานะเอกสารสำหรับตัวแทน", statusBody: "ข้อกำหนด เงื่อนไข และเอกสารประกอบยังไม่ได้รับการอนุมัติสำหรับการเผยแพร่" },
  contact: { title: "ติดต่อ MIKEO", intro: "หน้านี้จะแสดงช่องทางติดต่อทางธุรกิจที่ผ่านการยืนยัน ขณะนี้ยังไม่มีอีเมล หมายเลขโทรศัพท์ บัญชีข้อความ หรือ URL อย่างเป็นทางการสำหรับเผยแพร่", prepareTitle: "เตรียมข้อมูลสำหรับการติดต่อ", prepareBody: "คู่ค้าสามารถเตรียมข้อมูลเบื้องต้นเกี่ยวกับประเทศ ตลาด องค์กร และรูปแบบความร่วมมือที่สนใจไว้ล่วงหน้า", note: "จะเพิ่มแบบฟอร์มติดต่อเมื่อมีปลายทางและกระบวนการจัดการข้อมูลที่ผ่านการยืนยันแล้วเท่านั้น" },
  states: { loading: "กำลังโหลดหน้า…", errorTitle: "ไม่สามารถโหลดหน้านี้ได้", errorBody: "โปรดลองอีกครั้ง ยังไม่มีข้อมูลใดถูกส่งหรือเปลี่ยนแปลง", retry: "ลองอีกครั้ง", notFoundTitle: "ไม่พบหน้า", notFoundBody: "หน้านี้อาจถูกย้ายหรือที่อยู่อาจไม่ถูกต้อง", home: "กลับหน้าหลัก" },
};

export function getDictionary(locale: Locale): Dictionary {
  return locale === "th" ? th : en;
}
